# Generated by Django 4.1 on 2022-09-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delete_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.TextField()),
                ('brand', models.TextField()),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('active', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
