# Generated by Django 4.1 on 2022-09-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_delete_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('1', 'assinado'), ('2', 'Intermediário'), ('3', 'Avançado'), ('4', 'Intermediário'), ('5', 'Avançado')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(verbose_name=models.BooleanField()),
        ),
    ]
